"""first table

Revision ID: 1320d6eb0a31
Revises: 
Create Date: 2019-05-25 18:05:39.757944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1320d6eb0a31'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('finansowanie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rodzaj', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_finansowanie_rodzaj'), 'finansowanie', ['rodzaj'], unique=False)
    op.create_table('lekarz',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('imie', sa.String(length=255), nullable=False),
    sa.Column('nazwisko', sa.String(length=255), nullable=False),
    sa.Column('specjalizacja', sa.String(length=255), nullable=False),
    sa.Column('cena', sa.Float(precision=4), nullable=False),
    sa.Column('godzina_str', sa.String(length=255), nullable=False),
    sa.Column('godzina_kon', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('haslo', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_lekarz_cena'), 'lekarz', ['cena'], unique=False)
    op.create_index(op.f('ix_lekarz_email'), 'lekarz', ['email'], unique=True)
    op.create_index(op.f('ix_lekarz_godzina_kon'), 'lekarz', ['godzina_kon'], unique=False)
    op.create_index(op.f('ix_lekarz_godzina_str'), 'lekarz', ['godzina_str'], unique=False)
    op.create_index(op.f('ix_lekarz_imie'), 'lekarz', ['imie'], unique=False)
    op.create_index(op.f('ix_lekarz_nazwisko'), 'lekarz', ['nazwisko'], unique=False)
    op.create_index(op.f('ix_lekarz_specjalizacja'), 'lekarz', ['specjalizacja'], unique=False)
    op.create_table('pacjent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('imie', sa.String(length=255), nullable=False),
    sa.Column('nazwisko', sa.String(length=255), nullable=False),
    sa.Column('pesel', sa.Integer(), nullable=False),
    sa.Column('data_uro', sa.String(length=255), nullable=False),
    sa.Column('data_pw', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('haslo', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_pacjent_data_pw'), 'pacjent', ['data_pw'], unique=False)
    op.create_index(op.f('ix_pacjent_data_uro'), 'pacjent', ['data_uro'], unique=False)
    op.create_index(op.f('ix_pacjent_email'), 'pacjent', ['email'], unique=True)
    op.create_index(op.f('ix_pacjent_imie'), 'pacjent', ['imie'], unique=False)
    op.create_index(op.f('ix_pacjent_nazwisko'), 'pacjent', ['nazwisko'], unique=False)
    op.create_index(op.f('ix_pacjent_pesel'), 'pacjent', ['pesel'], unique=True)
    op.create_table('placowka',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('adres', sa.String(length=255), nullable=False),
    sa.Column('godzina_otw', sa.String(length=255), nullable=False),
    sa.Column('godzina_zam', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_placowka_adres'), 'placowka', ['adres'], unique=True)
    op.create_index(op.f('ix_placowka_godzina_otw'), 'placowka', ['godzina_otw'], unique=False)
    op.create_index(op.f('ix_placowka_godzina_zam'), 'placowka', ['godzina_zam'], unique=False)
    op.create_table('wizyta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('placowka_id', sa.Integer(), nullable=False),
    sa.Column('pacjent_id', sa.Integer(), nullable=False),
    sa.Column('lekarz_id', sa.Integer(), nullable=False),
    sa.Column('finansowanie_id', sa.Integer(), nullable=False),
    sa.Column('termin', sa.String(length=255), nullable=False),
    sa.Column('typ_wizyty', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['finansowanie_id'], ['finansowanie.id'], ),
    sa.ForeignKeyConstraint(['lekarz_id'], ['lekarz.id'], ),
    sa.ForeignKeyConstraint(['pacjent_id'], ['pacjent.id'], ),
    sa.ForeignKeyConstraint(['placowka_id'], ['placowka.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_wizyta_termin'), 'wizyta', ['termin'], unique=False)
    op.create_index(op.f('ix_wizyta_typ_wizyty'), 'wizyta', ['typ_wizyty'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wizyta_typ_wizyty'), table_name='wizyta')
    op.drop_index(op.f('ix_wizyta_termin'), table_name='wizyta')
    op.drop_table('wizyta')
    op.drop_index(op.f('ix_placowka_godzina_zam'), table_name='placowka')
    op.drop_index(op.f('ix_placowka_godzina_otw'), table_name='placowka')
    op.drop_index(op.f('ix_placowka_adres'), table_name='placowka')
    op.drop_table('placowka')
    op.drop_index(op.f('ix_pacjent_pesel'), table_name='pacjent')
    op.drop_index(op.f('ix_pacjent_nazwisko'), table_name='pacjent')
    op.drop_index(op.f('ix_pacjent_imie'), table_name='pacjent')
    op.drop_index(op.f('ix_pacjent_email'), table_name='pacjent')
    op.drop_index(op.f('ix_pacjent_data_uro'), table_name='pacjent')
    op.drop_index(op.f('ix_pacjent_data_pw'), table_name='pacjent')
    op.drop_table('pacjent')
    op.drop_index(op.f('ix_lekarz_specjalizacja'), table_name='lekarz')
    op.drop_index(op.f('ix_lekarz_nazwisko'), table_name='lekarz')
    op.drop_index(op.f('ix_lekarz_imie'), table_name='lekarz')
    op.drop_index(op.f('ix_lekarz_godzina_str'), table_name='lekarz')
    op.drop_index(op.f('ix_lekarz_godzina_kon'), table_name='lekarz')
    op.drop_index(op.f('ix_lekarz_email'), table_name='lekarz')
    op.drop_index(op.f('ix_lekarz_cena'), table_name='lekarz')
    op.drop_table('lekarz')
    op.drop_index(op.f('ix_finansowanie_rodzaj'), table_name='finansowanie')
    op.drop_table('finansowanie')
    # ### end Alembic commands ###
